version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
     script:
      - |
           echo "building my amazing repo..."
           mvn test
           export token=$(curl -H "Content-Type: application/json" -X POST --data "{ "client_id": "B9B92CC6655B4421B8B536A9FF318094","client_secret": "0332eddb162e3d6c1d5fddc8748a7363fc36f09e023dbcf4a141606e663bff15" }" https://xray.cloud.xpand-it.com/api/v1/authenticate| tr -d '"')
           echo $token
          
